# -*- coding: utf-8 -*-
"""cnn_brain_tumor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BdSsJMBAUZbIf6AomTM7milaWmbafddy
"""

import os
import pandas as pd
import numpy as np
from skimage.transform import resize
from skimage.io import imread
from keras.models import Sequential
from keras.layers import Conv2D,MaxPool2D,Flatten

os.listdir('/content/drive/MyDrive/Brain_Tumor/Training')

cn='/content/drive/MyDrive/Brain_Tumor/Training/pituitary'
len(os.listdir(cn))

cn1='/content/drive/MyDrive/Brain_Tumor/Training/notumor'
len(os.listdir(cn1))

cn2='/content/drive/MyDrive/Brain_Tumor/Training/meningioma'
len(os.listdir(cn2))

cn3='/content/drive/MyDrive/Brain_Tumor/Training/glioma'
len(os.listdir(cn3))

datadir='/content/drive/MyDrive/Brain_Tumor/Training'

x_train=[]
y_train=[]
categories=['glioma', 'pituitary', 'notumor', 'meningioma']

for i in categories:
    path = os.path.join(datadir, i)
    print(path)
    images = os.listdir(path)
    for img in images:
        img_path = os.path.join(path, img)
        img_array = imread(img_path)
        img_resize = resize(img_array, (150, 150, 1))
        x_train.append(img_resize)
        y_train.append(categories.index(i))

x_train=np.array(x_train)

